CREATE TABLE SYS_LOG (
   ID int(20) NOT NULL COMMENT 'ID',
   USERNAME VARCHAR(50) NULL COMMENT '用户名',
   OPERATION VARCHAR(50) NULL COMMENT '用户操作',
   TIME int(11) NULL COMMENT '响应时间',
   METHOD VARCHAR(200) NULL COMMENT '请求方法',
   PARAMS VARCHAR(500) NULL COMMENT '请求参数',
   IP VARCHAR(64) NULL COMMENT 'IP地址',
   CREATE_TIME DATE NULL COMMENT '创建时间'
);